ALTER TABLE accesses
    ADD COLUMN read_data BOOLEAN DEFAULT FALSE,
    ADD COLUMN delete_data BOOLEAN DEFAULT FALSE,
    ADD COLUMN create_data BOOLEAN DEFAULT FALSE,
    ADD COLUMN update_data BOOLEAN DEFAULT FALSE;
